package com.odysii.selenium.page;

public enum  FieldType {
    APPNAME, SUBTITLE, LANGUAGE, RETAILERS, AVAILABILITY, CATEGORY, KEYWORDS, PROMOTIONAL_TOKEN, SELECT_UPLOAD, NEW_VERSION_NUMBER, NEW_VERSION_TEXT, SCREEN_SHOTS_FILE
}
